### ISSUE TITLE
Release 1.1 tracking: Verification, changelog entries

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/sphinx_rtd_theme#1307]
For a list of open issues, see the 1.1 milestone: https://github.com/readthedocs/sphinx_rtd_theme/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.1

This is a meta-level issue to track that new PRs for 1.1 have a little extra verification since CI tests have had difficulties

* [x] https://github.com/readthedocs/sphinx_rtd_theme/pull/967 and https://github.com/readthedocs/sphinx_rtd_theme/pull/1330 - ~check with html4 writer~ the writer works, but the theme doesn't respect it and emits an html5 doctype regardless of the `html4_writer=True` config value.
* [x] https://github.com/readthedocs/sphinx_rtd_theme/pull/1116 - ~how old versions of pip accept setup.cfg?~ Edit: it's setuptools that generates the release package that's responsible for reading it, which it can do since 2016
* [x] https://github.com/readthedocs/sphinx_rtd_theme/pull/1080 - changelog entry missing
* [x] https://github.com/readthedocs/sphinx_rtd_theme/issues/1309 - changelog entry missing
* [x] https://github.com/readthedocs/sphinx_rtd_theme/pull/1215 - changelog entry missing
* [x] https://github.com/readthedocs/sphinx_rtd_theme/pull/1334 - changelog entry missing
* [x] https://github.com/readthedocs/sphinx_rtd_theme/pull/1084 - changelog entry missing
* [x] https://github.com/readthedocs/sphinx_rtd_theme/pull/1345 - changelog entry missing

Updates incoming for every PR that needs verification + changelog entry.

**Comment by benjaoming** [comment]
Releaseed!
